/**
 * Writes dist/_headers (Cloudflare Pages / Netlify format) after the build.
 *
 * The Content-Security-Policy is generated rather than hand-written, because
 * the site ships a handful of inline scripts — the pre-paint theme bootstrap,
 * Astro's view-transition glue, the Pagefind loader. A static policy would
 * have to allow 'unsafe-inline' to keep them working, which defeats most of
 * the point of having a CSP.
 *
 * Instead this scans every built HTML file, hashes each inline <script>, and
 * emits those hashes. Adding or editing an inline script changes its hash and
 * the policy follows automatically on the next build.
 *
 * Note on view transitions: Astro's ClientRouter appends an empty
 * `<script type="module" src="data:application/javascript,">` after each swap
 * as a script-ordering nudge. `data:` is deliberately NOT in script-src — it is
 * a well-known CSP bypass vector — so the browser blocks that one script and
 * logs a violation on each client-side navigation. Verified to be cosmetic:
 * inline-script re-execution, search and copy buttons behave identically with
 * the policy strict, with `data:` allowed, and with no CSP at all.
 *
 * Note on inline styles: 'unsafe-inline' is allowed for style-src. Astro is
 * configured with `inlineStylesheets: 'never'` so stylesheets are external,
 * but a few components set `style="..."` attributes, and CSP cannot hash
 * those. Style injection is a far weaker primitive than script injection, so
 * this is the accepted trade-off — documented in SECURITY.md.
 */
import { createHash } from 'node:crypto'
import { readFile, readdir, writeFile } from 'node:fs/promises'
import { join, resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

import { features } from '../src/config.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const dist = resolve(root, 'dist')

async function htmlFiles(dir) {
  const found = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) found.push(...(await htmlFiles(path)))
    else if (entry.name.endsWith('.html')) found.push(path)
  }
  return found
}

const files = await htmlFiles(dist)
const hashes = new Set()

// Inline scripts only — anything with a src= is external and covered by 'self'.
const scriptTag = /<script(?![^>]*\bsrc=)([^>]*)>([\s\S]*?)<\/script>/gi

for (const file of files) {
  const html = await readFile(file, 'utf8')
  for (const [, attrs, body] of html.matchAll(scriptTag)) {
    // Skip JSON-LD and other data blocks: CSP does not execute them.
    if (/\btype=("|')?(application\/(ld\+)?json)/i.test(attrs)) continue
    if (body.trim() === '') continue
    hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`)
  }
}

// giscus loads a script and embeds an iframe from its own origin.
const giscusEnabled =
  features.giscus.enabled && features.giscus.repo && features.giscus.repoId

// The contact form posts to a MailRelay worker on another origin and
// renders a Turnstile widget, which loads a script and an iframe from
// challenges.cloudflare.com. Miss any of these and the form fails only in
// production — `astro dev` never applies this policy, so the breakage does
// not reproduce locally.
// The site-key condition matches ContactForm.astro and contact.astro: the
// form does not render without one, so the policy must not widen either.
const mailrelay = features.mailrelay ?? {}
const mailrelayEnabled = Boolean(
  mailrelay.enabled &&
    mailrelay.workerOrigin &&
    mailrelay.endpointId &&
    mailrelay.turnstileSiteKey
)
const TURNSTILE = 'https://challenges.cloudflare.com'

const scriptSrc = [
  "'self'",
  ...hashes,
  ...(giscusEnabled ? ['https://giscus.app'] : []),
  ...(mailrelayEnabled ? [TURNSTILE] : []),
]
const connectSrc = [
  "'self'",
  ...(mailrelayEnabled ? [mailrelay.workerOrigin, TURNSTILE] : []),
]
const frameSrcOrigins = [
  ...(giscusEnabled ? ['https://giscus.app'] : []),
  ...(mailrelayEnabled ? [TURNSTILE] : []),
]
const frameSrc = frameSrcOrigins.length > 0 ? frameSrcOrigins : ["'none'"]

const csp = [
  `default-src 'self'`,
  `script-src ${scriptSrc.join(' ')}`,
  `style-src 'self' 'unsafe-inline'`,
  // Post content may embed remote images; that is the author's choice.
  `img-src 'self' data: https:`,
  `font-src 'self'`,
  `connect-src ${connectSrc.join(' ')}`,
  `frame-src ${frameSrc.join(' ')}`,
  `frame-ancestors 'none'`,
  `base-uri 'self'`,
  `form-action 'self'`,
  `object-src 'none'`,
  `upgrade-insecure-requests`,
].join('; ')

const headers = `# Generated by scripts/security-headers.mjs — do not edit by hand.
# Regenerated on every build; inline-script hashes change with their contents.

/*
  Content-Security-Policy: ${csp}
  Referrer-Policy: strict-origin-when-cross-origin
  X-Content-Type-Options: nosniff
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()
  Cross-Origin-Opener-Policy: same-origin
  Strict-Transport-Security: max-age=31536000; includeSubDomains

# Fingerprinted assets are immutable.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

# Share cards live at stable paths (/og/<slug>.png), so their contents change
# whenever a title, date or theme changes while the URL does not. Marking them
# immutable would pin a stale card in every browser that had seen the old one.
/og/*
  Cache-Control: public, max-age=3600, must-revalidate

/pagefind/*
  Cache-Control: public, max-age=3600

# HTML should revalidate so a new deploy is picked up immediately.
/*.html
  Cache-Control: public, max-age=0, must-revalidate
`

await writeFile(resolve(dist, '_headers'), headers)

console.log(
  `[headers] wrote dist/_headers — ${hashes.size} inline script hash(es) across ${files.length} page(s)` +
    (giscusEnabled ? ', giscus origins allowed' : '') +
    (mailrelayEnabled ? `, mailrelay (${mailrelay.workerOrigin}) + turnstile allowed` : '')
)
