/**
 * Writes dist/_headers (Cloudflare Pages / Netlify format) after the build.
 *
 * The Content-Security-Policy is generated rather than hand-written, because
 * the site ships a handful of inline scripts — the pre-paint theme bootstrap,
 * Astro's view-transition glue, the Pagefind loader. A static policy would
 * have to allow 'unsafe-inline' to keep them working, which defeats most of
 * the point of having a CSP.
 *
 * Instead this scans every built HTML file, hashes each inline <script>, and
 * emits those hashes. Adding or editing an inline script changes its hash and
 * the policy follows automatically on the next build.
 *
 * Note on inline styles: 'unsafe-inline' is allowed for style-src. Astro is
 * configured with `inlineStylesheets: 'never'` so stylesheets are external,
 * but a few components set `style="..."` attributes, and CSP cannot hash
 * those. Style injection is a far weaker primitive than script injection, so
 * this is the accepted trade-off — documented in SECURITY.md.
 */
import { createHash } from 'node:crypto'
import { readFile, readdir, writeFile } from 'node:fs/promises'
import { join, resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

import { features } from '../src/config.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const dist = resolve(root, 'dist')

async function htmlFiles(dir) {
  const found = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) found.push(...(await htmlFiles(path)))
    else if (entry.name.endsWith('.html')) found.push(path)
  }
  return found
}

const files = await htmlFiles(dist)
const hashes = new Set()

// Inline scripts only — anything with a src= is external and covered by 'self'.
const scriptTag = /<script(?![^>]*\bsrc=)([^>]*)>([\s\S]*?)<\/script>/gi

for (const file of files) {
  const html = await readFile(file, 'utf8')
  for (const [, attrs, body] of html.matchAll(scriptTag)) {
    // Skip JSON-LD and other data blocks: CSP does not execute them.
    if (/\btype=("|')?(application\/(ld\+)?json)/i.test(attrs)) continue
    if (body.trim() === '') continue
    hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`)
  }
}

// giscus loads a script and embeds an iframe from its own origin.
const giscusEnabled =
  features.giscus.enabled && features.giscus.repo && features.giscus.repoId

const scriptSrc = ["'self'", ...hashes, ...(giscusEnabled ? ['https://giscus.app'] : [])]
const frameSrc = giscusEnabled ? ['https://giscus.app'] : ["'none'"]

const csp = [
  `default-src 'self'`,
  `script-src ${scriptSrc.join(' ')}`,
  `style-src 'self' 'unsafe-inline'`,
  // Post content may embed remote images; that is the author's choice.
  `img-src 'self' data: https:`,
  `font-src 'self'`,
  `connect-src 'self'`,
  `frame-src ${frameSrc.join(' ')}`,
  `frame-ancestors 'none'`,
  `base-uri 'self'`,
  `form-action 'self'`,
  `object-src 'none'`,
  `upgrade-insecure-requests`,
].join('; ')

const headers = `# Generated by scripts/security-headers.mjs — do not edit by hand.
# Regenerated on every build; inline-script hashes change with their contents.

/*
  Content-Security-Policy: ${csp}
  Referrer-Policy: strict-origin-when-cross-origin
  X-Content-Type-Options: nosniff
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()
  Cross-Origin-Opener-Policy: same-origin
  Strict-Transport-Security: max-age=31536000; includeSubDomains

# Fingerprinted assets are immutable.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

/og/*
  Cache-Control: public, max-age=31536000, immutable

/pagefind/*
  Cache-Control: public, max-age=3600

# HTML should revalidate so a new deploy is picked up immediately.
/*.html
  Cache-Control: public, max-age=0, must-revalidate
`

await writeFile(resolve(dist, '_headers'), headers)

console.log(
  `[headers] wrote dist/_headers — ${hashes.size} inline script hash(es) across ${files.length} page(s)` +
    (giscusEnabled ? ', giscus origins allowed' : '')
)
